volumes:
  app_postgres_data:
    driver: local
  grafana_data:
    driver: local
  app_data:
    driver: local


services:
  app:
    build: .
    env_file: .env
    environment:
      PGHOST: app_postgres
      PGPORT: "5432"
    ports:
      - "8501:8501"
    volumes:
      - app_data:/app/data
    depends_on:
      app_postgres:
        condition: service_healthy


  app_postgres:
    image: pgvector/pgvector:pg18
    volumes:
      - app_postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./scripts/app_db_docker_entrypoint.sh:/docker-entrypoint-custom.sh:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "7432:5432"
    entrypoint: ["/docker-entrypoint-custom.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10


  grafana:
    image: grafana/grafana:11.2.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GRAFANA_PG_HOST: ${GRAFANA_PG_HOST}
      GRAFANA_PG_USER: ${GRAFANA_PG_USER}
      GRAFANA_PG_PASSWORD: ${GRAFANA_PG_PASSWORD}
      GRAFANA_DB_NAME: ${GRAFANA_DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      app_postgres:
        condition: service_healthy
