import os
import json
import time
import logging
import threading
from pathlib import Path
from typing import Any
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
from pydantic import BaseModel
from openai import OpenAI
from psycopg import sql
from tqdm.auto import tqdm

from db import get_connection, init_llm_evaluation_schema
from logging_config import configure_logging

configure_logging()
logger = logging.getLogger(__name__)


TABLE_NAME = os.getenv("TABLE_NAME", "employee_handbook")
GROUND_TRUTH_PATH = os.getenv("GROUND_TRUTH_PATH", "data/ground_truth.csv")
OUTPUT_DIR = Path(os.getenv("EVAL_OUTPUT_DIR", "data/evaluation"))

JUDGE_BASE_URL = os.getenv("JUDGE_BASE_URL")
JUDGE_MODEL = os.getenv("JUDGE_MODEL")
JUDGE_API_KEY = os.getenv("JUDGE_API_KEY")

MAX_WORKERS = int(os.getenv("MAX_WORKERS", "1"))
MAX_JUDGE_RPM = int(os.getenv("MAX_JUDGE_RPM", "10"))
MAX_RETRIES = int(os.getenv("MAX_RETRIES", "5"))
RETRY_BASE_DELAY = float(os.getenv("RETRY_BASE_DELAY", "2"))

NUM_RESULTS = int(os.getenv("NUM_RESULTS", "5"))

JUDGE_INSTRUCTIONS = """
You are an expert evaluator for a retrieval-augmented generation (RAG) system.
You will be given a question, an answer generated by the system, the retrieved context used to generate the answer, and the expected source document.

Score on three dimensions using a 1-5 scale:

1. FAITHFULNESS
- 5: Every claim in the answer is fully supported by the retrieved context.
- 4: Most claims are supported; minor unsupported generalizations that don't change the meaning.
- 3: Some claims are supported, but the answer includes notable unsupported information.
- 2: Most claims are unsupported or the answer fabricates significant details.
- 1: The answer is entirely unsupported by the retrieved context.

2. CONTEXT RELEVANCE
- 5: The retrieved context is highly relevant and directly addresses the question.
- 4: The context is mostly relevant with some useful information.
- 3: The context is partially relevant but missing key information.
- 2: The context has limited relevance to the question.
- 1: The context is unrelated to the question.

3. COMPLETENESS
- 5: The answer fully addresses the question using the available context.
- 4: The answer addresses most of the question with minor gaps.
- 3: The answer partially addresses the question but misses key points.
- 2: The answer barely addresses the question.
- 1: The answer does not address the question at all.

Provide a brief reasoning for each score.
""".strip()


class EvaluationScores(BaseModel):
    faithfulness_score: int
    faithfulness_reasoning: str
    context_relevance_score: int
    context_relevance_reasoning: str
    completeness_score: int
    completeness_reasoning: str


class RateLimiter:
    def __init__(self, max_requests_per_minute: int):
        self.max_requests = max_requests_per_minute
        self.window = 60.0
        self.timestamps: list[float] = []
        self.lock = threading.Lock()

    def wait(self):
        while True:
            with self.lock:
                now = time.monotonic()
                self.timestamps = [t for t in self.timestamps if t > now - self.window]

                if len(self.timestamps) < self.max_requests:
                    self.timestamps.append(now)
                    return

                sleep_until = self.timestamps[0] + self.window
                sleep_time = sleep_until - now

            if sleep_time > 0:
                logger.info("Rate limit: sleeping %.1fs", sleep_time)
                time.sleep(sleep_time)


def load_ground_truth(path: str = GROUND_TRUTH_PATH) -> list[dict[str, Any]]:
    df = pd.read_csv(path)

    required_columns = {"question", "document"}
    missing = required_columns - set(df.columns)
    if missing:
        raise ValueError(f"Ground truth file is missing required columns: {sorted(missing)}")

    df = df.dropna(subset=["question", "document"]).copy()
    df["question"] = df["question"].astype(str).str.strip()
    df["document"] = df["document"].astype(str).str.strip()
    df = df[(df["question"] != "") & (df["document"] != "")]

    return df.to_dict(orient="records")


def get_document_content(doc_path: str) -> str | None:
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                sql.SQL(
                    "SELECT content FROM {table} WHERE path = %s"
                ).format(table=sql.Identifier(TABLE_NAME)),
                (doc_path,),
            )
            row = cur.fetchone()
        return row[0] if row else None
    finally:
        conn.close()


def judge_answer(
    client: OpenAI,
    question: str,
    answer: str,
    retrieved_context: str,
    expected_document_content: str,
    limiter: RateLimiter,
) -> EvaluationScores | None:
    user_prompt = (
        f"QUESTION:\n{question}\n\n"
        f"ANSWER:\n{answer}\n\n"
        f"RETRIEVED CONTEXT:\n{retrieved_context}\n\n"
        f"EXPECTED SOURCE DOCUMENT:\n{expected_document_content}"
    )

    messages = [
        {"role": "developer", "content": JUDGE_INSTRUCTIONS},
        {"role": "user", "content": user_prompt},
    ]

    for attempt in range(MAX_RETRIES):
        try:
            limiter.wait()
            response = client.beta.chat.completions.parse(
                model=JUDGE_MODEL,
                messages=messages,
                response_format=EvaluationScores,
            )

            result = response.choices[0].message.parsed
            if result is None:
                logger.warning("Failed to parse judge response for question: %s", question[:80])
                return None

            return result

        except Exception as e:
            is_rate_limit = "429" in str(e) or "rate" in str(e).lower()
            if is_rate_limit and attempt < MAX_RETRIES - 1:
                delay = RETRY_BASE_DELAY * (2 ** attempt)
                logger.warning(
                    "Judge rate limited (attempt %d/%d), retrying in %.0fs...",
                    attempt + 1, MAX_RETRIES, delay,
                )
                time.sleep(delay)
            else:
                logger.error("Judge failed: %s", e)
                return None


def store_run(
    judge_model: str,
    evaluated_model: str,
    num_questions: int,
    config: dict[str, Any],
) -> int:
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                sql.SQL(
                    """
                    INSERT INTO llm_evaluation.evaluation_runs
                        (judge_model, evaluated_model, num_questions, config)
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                    """
                ),
                (judge_model, evaluated_model, num_questions, json.dumps(config)),
            )
            run_id = cur.fetchone()[0]
        conn.commit()
        return run_id
    finally:
        conn.close()


def store_result(
    run_id: int,
    message_id: int,
    expected_document: str,
    retrieved_context: str | None,
    scores: EvaluationScores,
):
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                sql.SQL(
                    """
                    INSERT INTO llm_evaluation.evaluation_results
                        (run_id, message_id, expected_document, retrieved_context,
                         faithfulness_score, faithfulness_reasoning,
                         context_relevance_score, context_relevance_reasoning,
                         completeness_score, completeness_reasoning)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """
                ),
                (
                    run_id,
                    message_id,
                    expected_document,
                    retrieved_context,
                    scores.faithfulness_score,
                    scores.faithfulness_reasoning,
                    scores.context_relevance_score,
                    scores.context_relevance_reasoning,
                    scores.completeness_score,
                    scores.completeness_reasoning,
                ),
            )
        conn.commit()
    finally:
        conn.close()


def evaluate_question(
    item: dict[str, Any],
    run_id: int,
    assistant,
    judge_client: OpenAI,
    limiter: RateLimiter,
) -> dict[str, Any] | None:
    question = item["question"]
    expected_doc = item["document"]

    expected_doc_content = get_document_content(expected_doc)
    if expected_doc_content is None:
        logger.warning("Document not found in DB: %s", expected_doc)
        return None

    search_results = assistant.search(question)
    retrieved_context = "\n\n".join(r.get("content", "") for r in search_results)

    try:
        rag_result = assistant.rag(
            question,
            conversation_id=item["_conversation_id"],
        )
    except Exception as e:
        logger.error("RAG failed for question '%s': %s", question[:80], e)
        return None

    message_id = rag_result.get("id")
    answer = rag_result.get("answer", "")

    if not message_id:
        logger.warning("No message_id returned for question: %s", question[:80])
        return None

    scores = judge_answer(judge_client, question, answer, retrieved_context, expected_doc_content, limiter)
    if scores is None:
        return None

    store_result(
        run_id=run_id,
        message_id=message_id,
        expected_document=expected_doc,
        retrieved_context=retrieved_context,
        scores=scores,
    )

    return {
        "question": question,
        "answer": answer,
        "expected_document": expected_doc,
        "faithfulness_score": scores.faithfulness_score,
        "faithfulness_reasoning": scores.faithfulness_reasoning,
        "context_relevance_score": scores.context_relevance_score,
        "context_relevance_reasoning": scores.context_relevance_reasoning,
        "completeness_score": scores.completeness_score,
        "completeness_reasoning": scores.completeness_reasoning,
    }


def save_outputs(detail_rows: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    detail_df = pd.DataFrame(detail_rows)
    detail_path = OUTPUT_DIR / "llm_evaluation_detail.csv"
    detail_df.to_csv(detail_path, index=False)

    summary_path = OUTPUT_DIR / "llm_evaluation_summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    logger.info("Saved detail to %s", detail_path)
    logger.info("Saved summary to %s", summary_path)


def main():
    logger.info("=== LLM Evaluation ===")

    if not JUDGE_BASE_URL or not JUDGE_MODEL or not JUDGE_API_KEY:
        logger.error("Set JUDGE_BASE_URL, JUDGE_MODEL, and JUDGE_API_KEY environment variables")
        return

    logger.info("Judge: %s at %s", JUDGE_MODEL, JUDGE_BASE_URL)
    logger.info("Workers: %d, Judge RPM: %d", MAX_WORKERS, MAX_JUDGE_RPM)

    init_llm_evaluation_schema()

    ground_truth = load_ground_truth()
    if not ground_truth:
        logger.error("No ground truth rows found.")
        return

    logger.info("Loaded %d ground truth questions", len(ground_truth))

    from assistant import create_assistant
    assistant = create_assistant()
    assistant.evaluator = None
    judge_client = OpenAI(base_url=JUDGE_BASE_URL, api_key=JUDGE_API_KEY)
    limiter = RateLimiter(MAX_JUDGE_RPM)

    conversation_id = assistant.chat_store.create_conversation(title="LLM Evaluation")

    evaluated_model = os.getenv("LLM_MODEL", "unknown")
    run_id = store_run(
        judge_model=JUDGE_MODEL,
        evaluated_model=evaluated_model,
        num_questions=len(ground_truth),
        config={"num_results": NUM_RESULTS, "max_workers": MAX_WORKERS, "max_judge_rpm": MAX_JUDGE_RPM},
    )
    logger.info("Created evaluation run %d", run_id)

    for item in ground_truth:
        item["_conversation_id"] = conversation_id

    detail_rows = []
    lock = threading.Lock()

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {
            executor.submit(
                evaluate_question, item, run_id, assistant, judge_client, limiter
            ): item
            for item in ground_truth
        }

        with tqdm(total=len(futures), desc="Evaluating") as pbar:
            for future in as_completed(futures):
                result = future.result()
                if result is not None:
                    with lock:
                        detail_rows.append(result)
                pbar.update(1)

    faithfulness_scores = [r["faithfulness_score"] for r in detail_rows]
    context_relevance_scores = [r["context_relevance_score"] for r in detail_rows]
    completeness_scores = [r["completeness_score"] for r in detail_rows]

    summary = {
        "run_id": run_id,
        "judge_model": JUDGE_MODEL,
        "evaluated_model": evaluated_model,
        "max_workers": MAX_WORKERS,
        "questions_evaluated": len(detail_rows),
        "avg_faithfulness": sum(faithfulness_scores) / len(faithfulness_scores) if faithfulness_scores else 0,
        "avg_context_relevance": sum(context_relevance_scores) / len(context_relevance_scores) if context_relevance_scores else 0,
        "avg_completeness": sum(completeness_scores) / len(completeness_scores) if completeness_scores else 0,
        "faithfulness_distribution": {str(i): faithfulness_scores.count(i) for i in range(1, 6)} if faithfulness_scores else {},
        "context_relevance_distribution": {str(i): context_relevance_scores.count(i) for i in range(1, 6)} if context_relevance_scores else {},
        "completeness_distribution": {str(i): completeness_scores.count(i) for i in range(1, 6)} if completeness_scores else {},
    }

    save_outputs(detail_rows, summary)

    print("\n" + "=" * 60)
    print("LLM EVALUATION RESULTS")
    print("=" * 60)
    print(f"Questions evaluated: {summary['questions_evaluated']}")
    print(f"Avg Faithfulness:       {summary['avg_faithfulness']:.2f} / 5")
    print(f"Avg Context Relevance:  {summary['avg_context_relevance']:.2f} / 5")
    print(f"Avg Completeness:       {summary['avg_completeness']:.2f} / 5")
    print(f"Faithfulness dist:      {summary['faithfulness_distribution']}")
    print(f"Context Relevance dist: {summary['context_relevance_distribution']}")
    print(f"Completeness dist:      {summary['completeness_distribution']}")
    print("=" * 60)


if __name__ == "__main__":
    main()
