import os
import time
import random
import logging
import threading
from queue import Queue
from typing import Any

from pydantic import BaseModel
from openai import OpenAI

from db import get_connection, init_llm_evaluation_schema

logger = logging.getLogger(__name__)

SAMPLE_RATE = float(os.getenv("EVAL_SAMPLE_RATE", "0.1"))
MAX_EVAL_RPM = int(os.getenv("MAX_EVAL_RPM", "10"))
MAX_RETRIES = int(os.getenv("MAX_RETRIES", "5"))
RETRY_BASE_DELAY = float(os.getenv("RETRY_BASE_DELAY", "2"))
JUDGE_COST_PER_INPUT_TOKEN = float(os.getenv("JUDGE_COST_PER_INPUT_TOKEN", "0"))
JUDGE_COST_PER_OUTPUT_TOKEN = float(os.getenv("JUDGE_COST_PER_OUTPUT_TOKEN", "0"))
EVAL_WORKERS = int(os.getenv("EVAL_WORKERS", "1"))

JUDGE_BASE_URL = os.getenv("JUDGE_BASE_URL")
JUDGE_MODEL = os.getenv("JUDGE_MODEL")
JUDGE_API_KEY = os.getenv("JUDGE_API_KEY")

JUDGE_INSTRUCTIONS = """
You are an expert evaluator for a retrieval-augmented generation (RAG) system.
You will be given a question, an answer generated by the system, and the retrieved context used to generate the answer.

Score on three dimensions using a 1-5 scale:

1. FAITHFULNESS
- 5: Every claim in the answer is fully supported by the retrieved context.
- 4: Most claims are supported; minor unsupported generalizations that don't change the meaning.
- 3: Some claims are supported, but the answer includes notable unsupported information.
- 2: Most claims are unsupported or the answer fabricates significant details.
- 1: The answer is entirely unsupported by the retrieved context.

2. CONTEXT RELEVANCE
- 5: The retrieved context is highly relevant and directly addresses the question.
- 4: The context is mostly relevant with some useful information.
- 3: The context is partially relevant but missing key information.
- 2: The context has limited relevance to the question.
- 1: The context is unrelated to the question.

3. COMPLETENESS
- 5: The answer fully addresses the question using the available context.
- 4: The answer addresses most of the question with minor gaps.
- 3: The answer partially addresses the question but misses key points.
- 2: The answer barely addresses the question.
- 1: The answer does not address the question at all.

Provide a brief reasoning for each score.
""".strip()


class EvaluationScores(BaseModel):
    faithfulness_score: int
    faithfulness_reasoning: str
    context_relevance_score: int
    context_relevance_reasoning: str
    completeness_score: int
    completeness_reasoning: str


class JudgeResult(BaseModel):
    scores: EvaluationScores
    input_tokens: int
    output_tokens: int
    cost: float


class RateLimiter:
    def __init__(self, max_requests_per_minute: int):
        self.max_requests = max_requests_per_minute
        self.window = 60.0
        self.timestamps: list[float] = []
        self.lock = threading.Lock()

    def wait(self):
        while True:
            with self.lock:
                now = time.monotonic()
                self.timestamps = [t for t in self.timestamps if t > now - self.window]
                if len(self.timestamps) < self.max_requests:
                    self.timestamps.append(now)
                    return
                sleep_until = self.timestamps[0] + self.window
                sleep_time = sleep_until - now
            if sleep_time > 0:
                logger.info("Eval rate limit: sleeping %.1fs", sleep_time)
                time.sleep(sleep_time)


class Evaluator:
    def __init__(self):
        self._enabled = bool(JUDGE_BASE_URL and JUDGE_MODEL and JUDGE_API_KEY)
        if not self._enabled:
            logger.warning("Evaluator disabled: set JUDGE_BASE_URL, JUDGE_MODEL, JUDGE_API_KEY")
            return

        self._client = OpenAI(base_url=JUDGE_BASE_URL, api_key=JUDGE_API_KEY)
        self._limiter = RateLimiter(MAX_EVAL_RPM)
        self._queue = Queue()
        self._workers = []
        self._init_schema()
        self._start_workers()
        logger.info(
            "Evaluator enabled: judge=%s, sample_rate=%.0f%%, rpm=%d, workers=%d",
            JUDGE_MODEL,
            SAMPLE_RATE * 100,
            MAX_EVAL_RPM,
            EVAL_WORKERS,
        )

    @staticmethod
    def _init_schema():
        try:
            init_llm_evaluation_schema()
        except Exception:
            logger.error("Failed to init evaluation schema", exc_info=True)

    def _start_workers(self):
        for i in range(max(1, EVAL_WORKERS)):
            t = threading.Thread(
                target=self._worker_loop,
                daemon=True,
                name=f"eval-worker-{i + 1}",
            )
            t.start()
            self._workers.append(t)

    def _worker_loop(self):
        while True:
            payload = self._queue.get()
            try:
                self._run_evaluation(**payload)
            except Exception:
                logger.exception("Evaluation worker failed")
            finally:
                self._queue.task_done()

    def evaluate(self, message_id: int, question: str, answer: str, retrieved_context: str):
        if not self._enabled:
            return
        if random.random() >= SAMPLE_RATE:
            return
        if self._already_evaluated(message_id):
            return

        self._queue.put(
            {
                "message_id": message_id,
                "question": question,
                "answer": answer,
                "retrieved_context": retrieved_context,
            }
        )

    def _already_evaluated(self, message_id: int) -> bool:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT 1 FROM llm_evaluation.evaluation_results WHERE message_id = %s LIMIT 1",
                    (message_id,),
                )
                return cur.fetchone() is not None

    def _run_evaluation(self, message_id: int, question: str, answer: str, retrieved_context: str):
        judge_result = self._judge(question, answer, retrieved_context)
        if judge_result is None:
            return

        run_id = self._get_or_create_run()
        self._store_result(run_id, message_id, retrieved_context, judge_result)

    def _judge(self, question: str, answer: str, retrieved_context: str) -> JudgeResult | None:
        user_prompt = (
            f"QUESTION:\n{question}\n\n"
            f"ANSWER:\n{answer}\n\n"
            f"RETRIEVED CONTEXT:\n{retrieved_context}"
        )
        messages = [
            {"role": "developer", "content": JUDGE_INSTRUCTIONS},
            {"role": "user", "content": user_prompt},
        ]

        for attempt in range(MAX_RETRIES):
            try:
                self._limiter.wait()
                response = self._client.beta.chat.completions.parse(
                    model=JUDGE_MODEL,
                    messages=messages,
                    response_format=EvaluationScores,
                )
                result = response.choices[0].message.parsed
                if result is None:
                    logger.warning("Failed to parse judge response")
                    return None

                usage = response.usage
                input_tokens = getattr(usage, "prompt_tokens", 0) if usage else 0
                output_tokens = getattr(usage, "completion_tokens", 0) if usage else 0
                cost = input_tokens * JUDGE_COST_PER_INPUT_TOKEN + output_tokens * JUDGE_COST_PER_OUTPUT_TOKEN
                return JudgeResult(
                    scores=result,
                    input_tokens=input_tokens,
                    output_tokens=output_tokens,
                    cost=cost,
                )
            except Exception as e:
                is_rate_limit = "429" in str(e) or "rate" in str(e).lower()
                if is_rate_limit and attempt < MAX_RETRIES - 1:
                    delay = RETRY_BASE_DELAY * (2 ** attempt)
                    logger.warning("Judge rate limited, retrying in %.0fs...", delay)
                    time.sleep(delay)
                else:
                    logger.error("Judge failed: %s", e)
                    return None

    def _get_or_create_run(self) -> int:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT id FROM llm_evaluation.evaluation_runs WHERE judge_model = %s ORDER BY id DESC LIMIT 1",
                    (JUDGE_MODEL,),
                )
                row = cur.fetchone()
                if row:
                    return row[0]

                cur.execute(
                    """
                    INSERT INTO llm_evaluation.evaluation_runs
                        (judge_model, evaluated_model, num_questions, config)
                    VALUES (%s, %s, 0, %s)
                    RETURNING id
                    """,
                    (
                        JUDGE_MODEL,
                        os.getenv("LLM_MODEL", "unknown"),
                        '{"type": "production"}',
                    ),
                )
                return cur.fetchone()[0]

    def _store_result(self, run_id: int, message_id: int, retrieved_context: str, judge_result: JudgeResult):
        scores = judge_result.scores
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO llm_evaluation.evaluation_results
                        (run_id, message_id, retrieved_context,
                         faithfulness_score, faithfulness_reasoning,
                         context_relevance_score, context_relevance_reasoning,
                         completeness_score, completeness_reasoning,
                         judge_input_tokens, judge_output_tokens, judge_cost)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        run_id,
                        message_id,
                        retrieved_context,
                        scores.faithfulness_score,
                        scores.faithfulness_reasoning,
                        scores.context_relevance_score,
                        scores.context_relevance_reasoning,
                        scores.completeness_score,
                        scores.completeness_reasoning,
                        judge_result.input_tokens,
                        judge_result.output_tokens,
                        judge_result.cost,
                    ),
                )
            logger.info("Stored evaluation for message %d", message_id)

    def get_correlation(self) -> list[dict[str, Any]]:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT
                        m.rating,
                        ROUND(AVG(er.faithfulness_score)::numeric, 2) AS avg_faithfulness,
                        ROUND(AVG(er.context_relevance_score)::numeric, 2) AS avg_context_relevance,
                        ROUND(AVG(er.completeness_score)::numeric, 2) AS avg_completeness,
                        COUNT(*) AS count
                    FROM llm_evaluation.evaluation_results er
                    JOIN chat.messages m ON m.id = er.message_id
                    WHERE m.rating IS NOT NULL
                    GROUP BY m.rating
                    ORDER BY m.rating
                    """
                )
                rows = cur.fetchall()
                return [
                    {
                        "rating": r[0],
                        "avg_faithfulness": float(r[1]),
                        "avg_context_relevance": float(r[2]),
                        "avg_completeness": float(r[3]),
                        "count": r[4],
                    }
                    for r in rows
                ]